// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFN0Kfa9W-dQrDdCP14m4EhDfZ9dyvwAE',
    appId: '1:1003811883410:web:afdfa967f4ff653f11d94b',
    messagingSenderId: '1003811883410',
    projectId: 'pos-infnet-a7b3b',
    authDomain: 'pos-infnet-a7b3b.firebaseapp.com',
    storageBucket: 'pos-infnet-a7b3b.appspot.com',
    measurementId: 'G-GX0LP0F8ML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9J8uKlWr88ZvLndyRF8-f7GHwNIONALs',
    appId: '1:1003811883410:android:d1c56ecc4dffdb6b11d94b',
    messagingSenderId: '1003811883410',
    projectId: 'pos-infnet-a7b3b',
    storageBucket: 'pos-infnet-a7b3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA-QBQc1uCukGVY9WK6Mx_Xpos3CVLG5I',
    appId: '1:1003811883410:ios:17e5169e0f89719e11d94b',
    messagingSenderId: '1003811883410',
    projectId: 'pos-infnet-a7b3b',
    storageBucket: 'pos-infnet-a7b3b.appspot.com',
    iosClientId:
        '1003811883410-3bfjeflpf7bfs1ovdokksc9aam7v67k2.apps.googleusercontent.com',
    iosBundleId: 'br.edu.infnet.al.lista10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA-QBQc1uCukGVY9WK6Mx_Xpos3CVLG5I',
    appId: '1:1003811883410:ios:17e5169e0f89719e11d94b',
    messagingSenderId: '1003811883410',
    projectId: 'pos-infnet-a7b3b',
    storageBucket: 'pos-infnet-a7b3b.appspot.com',
    iosClientId:
        '1003811883410-3bfjeflpf7bfs1ovdokksc9aam7v67k2.apps.googleusercontent.com',
    iosBundleId: 'br.edu.infnet.al.lista10',
  );
}
